version: '3.6'
services:
  mongo-test:
    container_name: ship-test-mongo
    image: mongo:4.2
    command: --replSet ship-test-rs --bind_ip_all
    networks:
      - ship-test
    ports:
      - 27018:27017
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mongo-replicator-test:
    container_name: ship-test-mongo-replicator
    build: ./mongo-replicator
    environment:
      - HOST=mongo-test
      - PORT=27017
      - REPLICA_SET_NAME=ship-test-rs
      - IMMORTAL=true
    networks:
      - ship-test
    depends_on:
      - mongo-test
  redis-test:
    container_name: ship-test-redis
    image: redis:5.0.5
    command: redis-server --appendonly yes
    hostname: redis
    networks:
      - ship-test
    ports:
      - 6380:6379
  api-test:
    container_name: ship-test-api
    command: npm test
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - ship-test
    environment:
      APP_ENV: test
    volumes:
      - ./src:/app/src
    ports:
      - 4001:3001
      - 9082:8082
    depends_on:
      - mongo-replicator-test
      - redis-test

networks:
  ship-test:
    name: ship-test-network
